version: 3.7

services:
  db:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"

volumes:
  dbdata:
